@base_address = http://localhost:8082/professors

# Bean Validation Check with multilingual
POST {{base_address}}/
Accept-Language: en
Content-Type: application/json

{
    "id":0,
    "name": "Sabarinathan S98",
    "department": "EE"
}
###
POST {{base_address}}/
Accept-Language: kn
Content-Type: application/json

{
    "id":0,
    "name": "Sabarinathan S98",
    "department": "EE"
}
###
POST {{base_address}}/
Accept-Language: ta
Content-Type: application/json

{
    "id":0,
    "name": "Sabarinathan S98",
    "department": "EE"
}
###
# Bean Validation Check
POST {{base_address}}/
Content-Type: application/json

{
    "id":-9,
    "name": "Sabarinathan S90",
    "department": "EE"
}

###

# Basic CRUD Check
GET {{base_address}}/

###

GET {{base_address}}/88

###

POST {{base_address}}/
Content-Type: application/json

{
  "id": 88,
  "name": "Rasheedha Mohamed S",
  "department": "CSE"
}

###

PUT {{base_address}}/88
Content-Type: application/json

{
  "id": 88,
  "name": "Rasheedha Mohamed R",
  "department": "CSE"
}

###

DELETE {{base_address}}/88